# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_musicplayer(object):
    def setupUi(self, musicplayer):
        musicplayer.setObjectName("musicplayer")
        musicplayer.resize(440, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(musicplayer.sizePolicy().hasHeightForWidth())
        musicplayer.setSizePolicy(sizePolicy)
        musicplayer.setMaximumSize(QtCore.QSize(440, 460))
        musicplayer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        musicplayer.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(musicplayer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("QWidget#centralwidget,#v_hint\n"
"{\n"
"    background-color: rgb(29, 29, 29);\n"
"    \n"
"}\n"
"\n"
"\n"
"#play_button\n"
"{\n"
" border-radius: 35%;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#play_button:hover\n"
"{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"#play_button:hover:pressed\n"
"{\n"
"    background-color:rgb(177, 177, 177);\n"
"\n"
"}\n"
"\n"
"#next_button\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"image: url(:/neuron_music/img/next.png);\n"
"}\n"
"#next_button:hover\n"
"{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"#next_button:hover:pressed\n"
"{\n"
"    \n"
"    background-color:rgb(177, 177, 177);\n"
"}\n"
"\n"
"#back_button\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 25px;\n"
"image: url(:/neuron_music/img/back.png);\n"
"}\n"
"\n"
"#back_button:hover\n"
"{\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"\n"
"}\n"
"\n"
"#back_button:hover:pressed\n"
"{\n"
"background-color:rgb(177, 177, 177);\n"
"\n"
"}\n"
"\n"
"#config\n"
"{\n"
"border-style: solid;\n"
"border-radius: 6px;\n"
"image:url(:/neuron_music/img/configuracion.png);\n"
"}\n"
"\n"
"#config:hover\n"
"{\n"
"    \n"
"    background-color: rgb(95, 95, 95);\n"
"\n"
"}\n"
"\n"
"#img_volumen\n"
"{\n"
"\n"
"border-radius: 3px;\n"
"image: url(:/neuron_music/img/volumen.png);\n"
"}\n"
"#img_volumen:hover:pressed\n"
"{\n"
"background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"\n"
"#config:hover:pressed,#config:hover:pressed\n"
"{\n"
"    \n"
"    background-color: rgb(50, 50, 50);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QSlider::groove:vertical {\n"
"    \n"
"    background-color: rgb(45, 45, 45);\n"
"    position: absolute;\n"
"    left: 7px; right: 7px;\n"
"\n"
"} \n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 10px;\n"
"  border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    margin: 0 -4px; \n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"   background-color: rgb(57, 57, 57);\n"
"\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px;\n"
"    border-radius:5px;\n"
"    background-color: rgb(230, 230, 230);\n"
" position: absolute;\n"
"    left: 7px; right: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"   \n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: -2px 0; \n"
"    border-radius: 6px;\n"
"    \n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"   border-radius: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.967412, y2:0, stop:0 rgba(21, 210, 169, 255), stop:1 rgba(159, 247, 172, 255));;\n"
"}\n"
"\n"
"#fondo_slider {\n"
"background-color: rgb(176, 176, 176);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"#img_pausa {\n"
"image: url(:/neuron_music/img/pausa.png);\n"
"}\n"
"\n"
"#nombre_cancion\n"
"{\n"
"color:qlineargradient(spread:reflect, x1:0.00921659, y1:1, x2:0.88, y2:0.148182, stop:0.364055 rgba(199, 199, 199, 255), stop:0.843318 rgba(255, 255, 255, 255))\n"
"\n"
"}\n"
"#nombre_cancion:hover\n"
"{\n"
"color:rgb(238, 238, 238);\n"
"\n"
"}\n"
"#files{\n"
"    image: url(:/neuron_music/img/outline_menu_white_48dp.png);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(199, 365, 70, 70))
        self.play_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/neuron_music/img/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon)
        self.play_button.setIconSize(QtCore.QSize(40, 40))
        self.play_button.setObjectName("play_button")
        self.control_volumen = QtWidgets.QSlider(self.centralwidget)
        self.control_volumen.setGeometry(QtCore.QRect(29, 280, 16, 71))
        self.control_volumen.setMaximum(101)
        self.control_volumen.setOrientation(QtCore.Qt.Vertical)
        self.control_volumen.setObjectName("control_volumen")
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(290, 377, 51, 51))
        self.next_button.setText("")
        self.next_button.setObjectName("next_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(125, 377, 51, 51))
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.time_inicio = QtWidgets.QLabel(self.centralwidget)
        self.time_inicio.setGeometry(QtCore.QRect(65, 360, 60, 21))
        self.time_inicio.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.time_inicio.setObjectName("time_inicio")
        self.time_final = QtWidgets.QLabel(self.centralwidget)
        self.time_final.setGeometry(QtCore.QRect(375, 360, 60, 21))
        self.time_final.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.time_final.setWordWrap(False)
        self.time_final.setObjectName("time_final")
        self.config = QtWidgets.QPushButton(self.centralwidget)
        self.config.setGeometry(QtCore.QRect(401, 11, 31, 21))
        self.config.setText("")
        self.config.setObjectName("config")
        self.img_volumen = QtWidgets.QLabel(self.centralwidget)
        self.img_volumen.setGeometry(QtCore.QRect(20, 360, 31, 21))
        self.img_volumen.setText("")
        self.img_volumen.setObjectName("img_volumen")
        self.slider_2 = QtWidgets.QSlider(self.centralwidget)
        self.slider_2.setGeometry(QtCore.QRect(64, 326, 341, 20))
        self.slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_2.setObjectName("slider_2")
        self.fondo_slider = QtWidgets.QLabel(self.centralwidget)
        self.fondo_slider.setGeometry(QtCore.QRect(60, 320, 351, 31))
        self.fondo_slider.setText("")
        self.fondo_slider.setObjectName("fondo_slider")
        self.v_hint = QtWidgets.QLabel(self.centralwidget)
        self.v_hint.setGeometry(QtCore.QRect(23, 270, 21, 81))
        self.v_hint.setText("")
        self.v_hint.setObjectName("v_hint")
        self.nombre_cancion = QtWidgets.QLabel(self.centralwidget)
        self.nombre_cancion.setGeometry(QtCore.QRect(60, 280, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.nombre_cancion.setFont(font)
        self.nombre_cancion.setTextFormat(QtCore.Qt.PlainText)
        self.nombre_cancion.setScaledContents(True)
        self.nombre_cancion.setAlignment(QtCore.Qt.AlignCenter)
        self.nombre_cancion.setWordWrap(False)
        self.nombre_cancion.setObjectName("nombre_cancion")
        self.cover = QtWidgets.QLabel(self.centralwidget)
        self.cover.setGeometry(QtCore.QRect(104, 80, 260, 160))
        self.cover.setText("")
        self.cover.setScaledContents(False)
        self.cover.setObjectName("cover")
        self.files = QtWidgets.QLabel(self.centralwidget)
        self.files.setGeometry(QtCore.QRect(360, 380, 31, 41))
        self.files.setText("")
        self.files.setObjectName("files")
        self.play_button.raise_()
        self.next_button.raise_()
        self.back_button.raise_()
        self.time_inicio.raise_()
        self.time_final.raise_()
        self.config.raise_()
        self.img_volumen.raise_()
        self.fondo_slider.raise_()
        self.slider_2.raise_()
        self.control_volumen.raise_()
        self.v_hint.raise_()
        self.nombre_cancion.raise_()
        self.cover.raise_()
        self.files.raise_()
        musicplayer.setCentralWidget(self.centralwidget)

        self.retranslateUi(musicplayer)
        QtCore.QMetaObject.connectSlotsByName(musicplayer)

    def retranslateUi(self, musicplayer):
        _translate = QtCore.QCoreApplication.translate
        musicplayer.setWindowTitle(_translate("musicplayer", "MainWindow"))
        self.time_inicio.setText(_translate("musicplayer", "<html><head/><body><p><span style=\" color:#ffffff;\">0:00</span></p></body></html>"))
        self.time_final.setText(_translate("musicplayer", "<html><head/><body><p><span style=\" color:#ffffff;\">0:00</span></p></body></html>"))
